create table if not exists public.potential_stock_records (
  id bigint generated by default as identity primary key,
  store_name text not null,
  record_order text not null,
  payload jsonb not null,
  inserted_at timestamptz not null default now()
);

create index if not exists potential_stock_records_store_order_idx
  on public.potential_stock_records (store_name, record_order);

create index if not exists potential_stock_records_payload_case_idx
  on public.potential_stock_records ((payload->>'case_id'));

create index if not exists potential_stock_records_payload_date_idx
  on public.potential_stock_records ((payload->>'trading_date'));
